### PR TITLE
adding credits at the end

### PR DESCRIPTION
**Pull request by rbanick**

### CODE REVIEW

**Comment by DenisCarriere** [comment]
You should of been able to simply just commit it instead of a pull request.. anyways I'll just add it :+1:

**Comment by rbanick** [comment]
Oh yeah, it's just a longtime habit drilled into me. "Never commit to master, always PR".

**Comment by DenisCarriere** [comment]
Oh thanks! I've only been using Github for about 2 years now, I guess I haven't got those habits drilled into me :)

**Comment by rbanick** [comment]
It helps having a former software developer as your boss ;)

**Comment by DenisCarriere** [comment]
That does help! I am one of the unique ones at my work that have talent in both GIS & Python

**Pull request merged**
